"""
Tests for CookieManager.

Tests issue #4: Refactor cookie handling into shared CookieManager.
"""

import os
import platform
import tempfile
from pathlib import Path
from unittest.mock import Mock, patch

import pytest

from utils.cookie_manager import CookieManager


@pytest.fixture
def cookie_manager():
    """Create a CookieManager instance for testing."""
    return CookieManager(verbose=False)


class TestCookieManager:
    """Test CookieManager functionality."""

    def test_initialization(self, cookie_manager):
        """Test that CookieManager initializes correctly."""
        assert cookie_manager is not None
        assert cookie_manager.verbose is False

    def test_initialization_with_config_and_logger(self):
        """Test initialization with config and logger."""
        mock_config = Mock()
        mock_logger = Mock()
        manager = CookieManager(config=mock_config, verbose=True, logger=mock_logger)
        assert manager.config == mock_config
        assert manager.verbose is True
        assert manager.logger == mock_logger

    def test_get_browser_list_macos(self, cookie_manager):
        """Test get_browser_list returns correct order for macOS."""
        with patch("platform.system", return_value="Darwin"):
            browsers = cookie_manager.get_browser_list()
            assert browsers == ("chrome", "safari", "firefox", "edge")
            assert isinstance(browsers, tuple)

    def test_get_browser_list_linux(self, cookie_manager):
        """Test get_browser_list returns correct order for Linux."""
        with patch("platform.system", return_value="Linux"):
            browsers = cookie_manager.get_browser_list()
            assert browsers == ("chrome", "firefox", "safari", "edge")
            assert isinstance(browsers, tuple)

    def test_get_browser_list_windows(self, cookie_manager):
        """Test get_browser_list returns correct order for Windows."""
        with patch("platform.system", return_value="Windows"):
            browsers = cookie_manager.get_browser_list()
            assert browsers == ("chrome", "firefox", "safari", "edge")
            assert isinstance(browsers, tuple)

    def test_filter_youtube_cookies(self, cookie_manager):
        """Test filtering YouTube cookies from cookie list."""
        cookies = [
            {"domain": "youtube.com", "name": "test1", "value": "value1"},
            {"domain": ".youtube.com", "name": "test2", "value": "value2"},
            {"domain": "google.com", "name": "test3", "value": "value3"},
            {"domain": "example.com", "name": "test4", "value": "value4"},
        ]

        filtered = cookie_manager._filter_youtube_cookies(cookies)
        assert len(filtered) == 2
        assert filtered[0]["domain"] == "youtube.com"
        assert filtered[1]["domain"] == ".youtube.com"

    def test_filter_youtube_cookies_empty(self, cookie_manager):
        """Test filtering with no YouTube cookies."""
        cookies = [
            {"domain": "google.com", "name": "test1", "value": "value1"},
            {"domain": "example.com", "name": "test2", "value": "value2"},
        ]

        filtered = cookie_manager._filter_youtube_cookies(cookies)
        assert len(filtered) == 0

    def test_save_cookies_to_netscape_file(self, cookie_manager):
        """Test saving cookies to Netscape format file."""
        cookies = [
            {
                "domain": ".youtube.com",
                "path": "/",
                "secure": True,
                "expires": 1234567890,
                "name": "test_cookie",
                "value": "test_value",
            },
            {
                "domain": "youtube.com",
                "path": "/watch",
                "secure": False,
                "expires": 0,
                "name": "another_cookie",
                "value": "another_value",
            },
        ]

        with tempfile.NamedTemporaryFile(mode="w", delete=False, suffix=".txt") as tmp:
            tmp_path = tmp.name

        try:
            result = cookie_manager.save_cookies_to_netscape_file(cookies, tmp_path)

            assert result == tmp_path

            # Read and verify file contents
            with open(tmp_path, "r") as f:
                content = f.read()

            assert "# Netscape HTTP Cookie File" in content
            assert "# This file was generated by spatelier" in content
            assert ".youtube.com" in content
            assert "youtube.com" in content
            assert "test_cookie" in content
            assert "test_value" in content

            # Verify Netscape format
            lines = content.strip().split("\n")
            cookie_lines = [l for l in lines if l and not l.startswith("#")]
            assert len(cookie_lines) == 2

            # Check first cookie format
            first_cookie = cookie_lines[0].split("\t")
            assert len(first_cookie) == 7
            assert first_cookie[0] == ".youtube.com"
            assert first_cookie[1] == "TRUE"  # domain flag
            assert first_cookie[2] == "/"
            assert first_cookie[3] == "TRUE"  # secure
            assert first_cookie[4] == "1234567890"  # expires
            assert first_cookie[5] == "test_cookie"
            assert first_cookie[6] == "test_value"

        finally:
            import os

            if os.path.exists(tmp_path):
                os.unlink(tmp_path)

    def test_save_cookies_to_netscape_file_temp(self, cookie_manager):
        """Test saving cookies to temporary file (no path provided)."""
        cookies = [
            {
                "domain": ".youtube.com",
                "path": "/",
                "secure": True,
                "expires": 1234567890,
                "name": "test_cookie",
                "value": "test_value",
            }
        ]

        result = cookie_manager.save_cookies_to_netscape_file(cookies)

        assert result is not None
        assert isinstance(result, str)

        # Verify file exists and has content
        import os

        assert os.path.exists(result)
        with open(result, "r") as f:
            content = f.read()
            assert "# Netscape HTTP Cookie File" in content

        # Clean up
        os.unlink(result)

    def test_save_cookies_to_netscape_file_error_handling(self, cookie_manager):
        """Test error handling when saving cookies fails."""
        cookies = [{"invalid": "cookie"}]

        # Mock tempfile to raise an error
        with patch("tempfile.NamedTemporaryFile", side_effect=Exception("Test error")):
            result = cookie_manager.save_cookies_to_netscape_file(cookies)
            assert result is None

    @patch("platform.system")
    def test_refresh_youtube_cookies_not_macos(self, mock_system, cookie_manager):
        """Test refresh_youtube_cookies returns None on non-macOS."""
        mock_system.return_value = "Linux"
        result = cookie_manager.refresh_youtube_cookies()
        assert result is None

    @patch("platform.system")
    @patch("os.path.exists")
    def test_refresh_youtube_cookies_no_chrome(self, mock_exists, mock_system, cookie_manager):
        """Test refresh_youtube_cookies returns None when Chrome not found."""
        mock_system.return_value = "Darwin"
        mock_exists.return_value = False
        result = cookie_manager.refresh_youtube_cookies()
        assert result is None

    @patch("platform.system")
    @patch("os.path.exists")
    def test_refresh_youtube_cookies_import_error(
        self, mock_exists, mock_system, cookie_manager
    ):
        """Test refresh_youtube_cookies handles ImportError when Playwright not available."""
        mock_system.return_value = "Darwin"
        mock_exists.return_value = True

        # Mock the import to raise ImportError
        with patch.dict("sys.modules", {"playwright.sync_api": None}):
            with patch("builtins.__import__", side_effect=ImportError("No module named 'playwright'")):
                result = cookie_manager.refresh_youtube_cookies()
                # Should return None when Playwright is not available
                assert result is None

    @patch("platform.system")
    @patch("os.path.exists")
    def test_refresh_youtube_cookies_no_playwright(self, mock_exists, mock_system, cookie_manager):
        """Test refresh_youtube_cookies handles missing Playwright gracefully."""
        mock_system.return_value = "Darwin"
        mock_exists.return_value = True

        # Mock the import to raise ImportError
        with patch.dict("sys.modules", {"playwright.sync_api": None}):
            # Force ImportError by making the import fail
            with patch("builtins.__import__", side_effect=ImportError("No module named 'playwright'")):
                result = cookie_manager.refresh_youtube_cookies()
                # Should return None when Playwright is not available
                assert result is None

    def test_are_cookies_valid_with_future_expiration(self, cookie_manager):
        """Test _are_cookies_valid returns True for cookies with future expiration."""
        import time
        
        # Create a cookie file with future expiration
        future_expires = int(time.time()) + 7200  # 2 hours from now
        cookie_file = cookie_manager.cookies_dir / "test_cookies.txt"
        
        with open(cookie_file, "w") as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write(f".youtube.com\tTRUE\t/\tTRUE\t{future_expires}\ttest_cookie\ttest_value\n")
        
        assert cookie_manager._are_cookies_valid(cookie_file) is True
        cookie_file.unlink()

    def test_are_cookies_valid_with_expired_cookies(self, cookie_manager):
        """Test _are_cookies_valid returns False for expired cookies."""
        import time
        
        # Create a cookie file with past expiration
        past_expires = int(time.time()) - 3600  # 1 hour ago
        cookie_file = cookie_manager.cookies_dir / "test_cookies.txt"
        
        with open(cookie_file, "w") as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write(f".youtube.com\tTRUE\t/\tTRUE\t{past_expires}\ttest_cookie\ttest_value\n")
        
        assert cookie_manager._are_cookies_valid(cookie_file) is False
        cookie_file.unlink()

    def test_are_cookies_valid_with_session_cookie(self, cookie_manager):
        """Test _are_cookies_valid returns True for session cookies (expires=0)."""
        cookie_file = cookie_manager.cookies_dir / "test_cookies.txt"
        
        with open(cookie_file, "w") as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write(".youtube.com\tTRUE\t/\tTRUE\t0\ttest_cookie\ttest_value\n")
        
        assert cookie_manager._are_cookies_valid(cookie_file) is True
        cookie_file.unlink()

    def test_get_cached_cookie_file_returns_valid_cache(self, cookie_manager):
        """Test _get_cached_cookie_file returns path when cache is valid."""
        import time
        
        # Create valid cached cookie file
        future_expires = int(time.time()) + 7200
        cookie_file = cookie_manager._cached_cookie_file
        
        with open(cookie_file, "w") as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write(f".youtube.com\tTRUE\t/\tTRUE\t{future_expires}\ttest_cookie\ttest_value\n")
        
        result = cookie_manager._get_cached_cookie_file()
        assert result == str(cookie_file)
        cookie_file.unlink()

    def test_get_cached_cookie_file_removes_expired_cache(self, cookie_manager):
        """Test _get_cached_cookie_file removes expired cache file."""
        import time
        
        # Create expired cached cookie file
        past_expires = int(time.time()) - 3600
        cookie_file = cookie_manager._cached_cookie_file
        
        with open(cookie_file, "w") as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write(f".youtube.com\tTRUE\t/\tTRUE\t{past_expires}\ttest_cookie\ttest_value\n")
        
        result = cookie_manager._get_cached_cookie_file()
        assert result is None
        assert not cookie_file.exists()  # Should be removed

    def test_get_youtube_cookies_uses_cache_when_valid(self, cookie_manager):
        """Test get_youtube_cookies uses cached cookies when valid."""
        import time
        
        # Create valid cached cookie file
        future_expires = int(time.time()) + 7200
        cookie_file = cookie_manager._cached_cookie_file
        
        with open(cookie_file, "w") as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write(f".youtube.com\tTRUE\t/\tTRUE\t{future_expires}\ttest_cookie\ttest_value\n")
        
        result = cookie_manager.get_youtube_cookies()
        assert result == str(cookie_file)
        cookie_file.unlink()

    @patch("platform.system")
    @patch("os.path.exists")
    def test_get_youtube_cookies_refreshes_when_no_cache(self, mock_exists, mock_system, cookie_manager):
        """Test get_youtube_cookies refreshes when no valid cache exists."""
        mock_system.return_value = "Darwin"
        mock_exists.return_value = False  # No Chrome
        
        # No cached file exists
        result = cookie_manager.get_youtube_cookies()
        # Should return None since Chrome not found
        assert result is None

    def test_cleanup_cookie_files_removes_temporary_files(self, cookie_manager):
        """Test cleanup_cookie_files removes temporary files."""
        import tempfile
        
        # Create a temporary cookie file and track it
        temp_file = tempfile.NamedTemporaryFile(mode="w", suffix=".txt", delete=False)
        temp_file.write("# Test cookie file\n")
        temp_file.close()
        
        cookie_manager._created_cookie_files.add(temp_file.name)
        
        # Cleanup should remove the temp file
        cleaned = cookie_manager.cleanup_cookie_files(keep_cached=True)
        assert cleaned == 1
        assert not os.path.exists(temp_file.name)

    def test_cleanup_cookie_files_preserves_cached_file(self, cookie_manager):
        """Test cleanup_cookie_files preserves cached cookie file."""
        import time
        
        # Create cached cookie file
        future_expires = int(time.time()) + 7200
        cookie_file = cookie_manager._cached_cookie_file
        
        with open(cookie_file, "w") as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write(f".youtube.com\tTRUE\t/\tTRUE\t{future_expires}\ttest_cookie\ttest_value\n")
        
        # Track it (simulating it was created)
        cookie_manager._created_cookie_files.add(str(cookie_file))
        
        # Cleanup with keep_cached=True should preserve it
        cleaned = cookie_manager.cleanup_cookie_files(keep_cached=True)
        assert cleaned == 0  # Cached file not removed
        assert cookie_file.exists()  # Still exists
        
        cookie_file.unlink()

    def test_get_browser_user_data_dir_chrome_macos(self, cookie_manager):
        """Test _get_browser_user_data_dir finds Chrome on macOS."""
        with patch("platform.system", return_value="Darwin"):
            with patch("pathlib.Path.exists", return_value=True):
                path = cookie_manager._get_browser_user_data_dir("chrome")
                assert path is not None
                assert "Chrome" in str(path)

    def test_get_browser_user_data_dir_firefox_linux(self, cookie_manager):
        """Test _get_browser_user_data_dir finds Firefox on Linux."""
        with patch("platform.system", return_value="Linux"):
            with patch("pathlib.Path.exists", return_value=True):
                path = cookie_manager._get_browser_user_data_dir("firefox")
                assert path is not None
                assert "firefox" in str(path).lower()

    def test_get_browser_user_data_dir_not_found(self, cookie_manager):
        """Test _get_browser_user_data_dir returns None when browser not found."""
        with patch("pathlib.Path.exists", return_value=False):
            path = cookie_manager._get_browser_user_data_dir("chrome")
            assert path is None

    def test_get_browser_user_data_dir_invalid_browser(self, cookie_manager):
        """Test _get_browser_user_data_dir returns None for invalid browser."""
        path = cookie_manager._get_browser_user_data_dir("invalid_browser")
        assert path is None

    def test_get_playwright_browser_type(self, cookie_manager):
        """Test _get_playwright_browser_type returns correct browser types."""
        # This method doesn't import playwright, just returns a mapping
        assert cookie_manager._get_playwright_browser_type("chrome") == "chromium"
        assert cookie_manager._get_playwright_browser_type("edge") == "chromium"
        assert cookie_manager._get_playwright_browser_type("firefox") == "firefox"
        assert cookie_manager._get_playwright_browser_type("safari") == "webkit"
        assert cookie_manager._get_playwright_browser_type("invalid") is None

    @patch("platform.system")
    def test_refresh_youtube_cookies_tries_multiple_browsers(self, mock_system, cookie_manager):
        """Test refresh_youtube_cookies tries browsers in order until one works."""
        mock_system.return_value = "Darwin"
        
        # Mock Playwright import to fail (not available in test env)
        with patch.dict("sys.modules", {"playwright.sync_api": None}):
            with patch("builtins.__import__", side_effect=ImportError("No module named 'playwright'")):
                result = cookie_manager.refresh_youtube_cookies()
                # Should return None when Playwright not available
                assert result is None
