"""Initial migration - create all tables

Revision ID: 4b58c98a7204
Revises:
Create Date: 2025-10-16 11:43:11.438064

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = "4b58c98a7204"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _index_exists(conn: sa.engine.Connection, table: str, index_name: str) -> bool:
    """Return True if the given index exists on the table."""
    insp = inspect(conn)
    for idx in insp.get_indexes(table):
        if idx.get("name") == index_name:
            return True
    return False


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    drop_media_file_id = _index_exists(conn, "processing_jobs", "ix_processing_jobs_media_file_id")
    create_id_index = not _index_exists(conn, "processing_jobs", "ix_processing_jobs_id")
    # Use batch_alter_table so SQLite works (SQLite does not support ALTER COLUMN).
    with op.batch_alter_table("processing_jobs", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.INTEGER(),
            nullable=False,
            autoincrement=True,
        )
        batch_op.alter_column(
            "status",
            existing_type=sa.VARCHAR(length=50),
            type_=sa.Enum(
                "PENDING",
                "PROCESSING",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                name="processingstatus",
            ),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "duration_seconds",
            existing_type=sa.REAL(),
            type_=sa.Float(),
            existing_nullable=True,
        )
        if drop_media_file_id:
            batch_op.drop_index(op.f("ix_processing_jobs_media_file_id"))
        if create_id_index:
            batch_op.create_index(
                op.f("ix_processing_jobs_id"), ["id"], unique=False
            )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    drop_id_index = _index_exists(conn, "processing_jobs", "ix_processing_jobs_id")
    create_media_file_id = not _index_exists(conn, "processing_jobs", "ix_processing_jobs_media_file_id")
    with op.batch_alter_table("processing_jobs", schema=None) as batch_op:
        if drop_id_index:
            batch_op.drop_index(op.f("ix_processing_jobs_id"))
        if create_media_file_id:
            batch_op.create_index(
                op.f("ix_processing_jobs_media_file_id"),
                ["media_file_id"],
                unique=False,
            )
        batch_op.alter_column(
            "duration_seconds",
            existing_type=sa.Float(),
            type_=sa.REAL(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "status",
            existing_type=sa.Enum(
                "PENDING",
                "PROCESSING",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                name="processingstatus",
            ),
            type_=sa.VARCHAR(length=50),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "id",
            existing_type=sa.INTEGER(),
            nullable=True,
            autoincrement=True,
        )
    # ### end Alembic commands ###
